from __future__ import annotations

from .models import ActionType, Difficulty, EvidenceItem, Scenario, Verdict


SCENARIOS: list[Scenario] = [
    Scenario(
        id="easy_reused_image_bridge",
        difficulty=Difficulty.EASY,
        claim="Breaking: Main bridge in Kherson was destroyed today by a fresh missile strike. Viral image attached.",
        source_name="WarFlashNow",
        source_type="viral social account",
        region="Kherson",
        timestamp="2026-04-01T10:00:00Z",
        verdict=Verdict.MISLEADING,
        rationale="The bridge damage image is authentic but from an older flood event, not from the claimed strike today.",
        evidence=[
            EvidenceItem(id="src_history", title="Source credibility record", summary="Account has posted sensational claims that were later corrected.", supports_truth=True, useful_actions=[ActionType.INSPECT_SOURCE], reliability=0.78),
            EvidenceItem(id="timeline_mismatch", title="Timeline mismatch", summary="Image traces point to first upload in 2023 during flooding.", supports_truth=True, useful_actions=[ActionType.CHECK_TIMELINE, ActionType.ANALYZE_MEDIA], reliability=0.96),
            EvidenceItem(id="trusted_report", title="Trusted outlet bulletin", summary="Local reporters confirm the bridge is still standing after today's alerts.", supports_truth=True, useful_actions=[ActionType.CROSSCHECK_TRUSTED_REPORTS], reliability=0.93),
            EvidenceItem(id="viral_reposts", title="Viral repost count", summary="Thousands of reposts repeat the same claim without new evidence.", supports_truth=False, useful_actions=[ActionType.REQUEST_CONTEXT], reliability=0.15, distractor=True),
        ],
    ),
    Scenario(
        id="easy_false_curfew_notice",
        difficulty=Difficulty.EASY,
        claim="Emergency message says a citywide curfew begins in 30 minutes after artillery strikes.",
        source_name="Forwarded WhatsApp Message",
        source_type="private forward",
        region="Haifa",
        timestamp="2026-04-02T18:15:00Z",
        verdict=Verdict.FAKE,
        rationale="The warning mimics official language, but authorities never issued it and the sender copied an old template.",
        evidence=[
            EvidenceItem(id="source_unknown", title="Unknown original sender", summary="The message has no attributable authority and uses a personal forwarding chain.", supports_truth=True, useful_actions=[ActionType.INSPECT_SOURCE], reliability=0.84),
            EvidenceItem(id="official_denial", title="Official denial", summary="Civil defense agency states there is no curfew order and labels the message false.", supports_truth=True, useful_actions=[ActionType.CROSSCHECK_TRUSTED_REPORTS], reliability=0.99),
            EvidenceItem(id="template_reuse", title="Old template reuse", summary="Nearly identical message circulated in another city months earlier.", supports_truth=True, useful_actions=[ActionType.CHECK_TIMELINE, ActionType.REQUEST_CONTEXT], reliability=0.9),
        ],
    ),
    Scenario(
        id="easy_real_evacuation_notice",
        difficulty=Difficulty.EASY,
        claim="Local authorities have opened two evacuation corridors after overnight shelling.",
        source_name="Regional Emergency Office",
        source_type="government channel",
        region="Sumy",
        timestamp="2026-04-03T06:20:00Z",
        verdict=Verdict.REAL,
        rationale="The claim matches official notices and independent reporting on corridor locations and opening times.",
        evidence=[
            EvidenceItem(id="official_post", title="Official emergency post", summary="Verified government channel posts route details and hotline numbers.", supports_truth=True, useful_actions=[ActionType.INSPECT_SOURCE, ActionType.CROSSCHECK_TRUSTED_REPORTS], reliability=0.99),
            EvidenceItem(id="local_reporters", title="Independent local confirmation", summary="Local radio and humanitarian volunteers confirm corridor opening.", supports_truth=True, useful_actions=[ActionType.CROSSCHECK_TRUSTED_REPORTS], reliability=0.94),
            EvidenceItem(id="language_neutral", title="Neutral language pattern", summary="Message includes logistical details, not vague emotional amplification.", supports_truth=True, useful_actions=[ActionType.SCAN_LANGUAGE], reliability=0.72),
        ],
    ),
    Scenario(
        id="medium_partial_strike_claim",
        difficulty=Difficulty.MEDIUM,
        claim="A viral thread claims the city hospital was completely destroyed and all services have collapsed.",
        source_name="ConflictWatchLive",
        source_type="aggregator",
        region="Gaza",
        timestamp="2026-04-01T14:30:00Z",
        verdict=Verdict.MISLEADING,
        rationale="A strike damaged one wing and disrupted service, but the claim exaggerates total destruction and full collapse.",
        evidence=[
            EvidenceItem(id="source_style", title="Source amplification pattern", summary="Aggregator often posts urgent updates before verification.", supports_truth=True, useful_actions=[ActionType.INSPECT_SOURCE], reliability=0.8),
            EvidenceItem(id="hospital_statement", title="Hospital operations update", summary="Hospital confirms damage to one wing while emergency services continue in reduced mode.", supports_truth=True, useful_actions=[ActionType.CROSSCHECK_TRUSTED_REPORTS], reliability=0.95),
            EvidenceItem(id="video_clip", title="Short video clip", summary="Clip shows smoke and panic but does not prove whole-building destruction.", supports_truth=True, useful_actions=[ActionType.ANALYZE_MEDIA], reliability=0.66),
            EvidenceItem(id="emotional_caption", title="Emotional wording", summary="Thread uses absolutes like 'wiped out' despite sparse evidence.", supports_truth=True, useful_actions=[ActionType.SCAN_LANGUAGE], reliability=0.71),
        ],
    ),
    Scenario(
        id="medium_old_video_convoy",
        difficulty=Difficulty.MEDIUM,
        claim="Video proves a new foreign military convoy entered the border today.",
        source_name="GeoAlert Forum",
        source_type="community forum",
        region="Poland border",
        timestamp="2026-03-31T09:45:00Z",
        verdict=Verdict.FAKE,
        rationale="The convoy video is old, from a training exercise two years earlier, and unrelated to today's border updates.",
        evidence=[
            EvidenceItem(id="forum_source", title="Community forum sourcing", summary="Original uploader cites 'friend of a friend' and provides no time stamp.", supports_truth=True, useful_actions=[ActionType.INSPECT_SOURCE], reliability=0.74),
            EvidenceItem(id="reverse_match", title="Archive video match", summary="Frames match a defense ministry video from 2024 training drills.", supports_truth=True, useful_actions=[ActionType.ANALYZE_MEDIA, ActionType.CHECK_TIMELINE], reliability=0.98),
            EvidenceItem(id="border_report", title="Border monitoring summary", summary="Trusted monitors report normal freight flow with no unusual convoy today.", supports_truth=True, useful_actions=[ActionType.CROSSCHECK_TRUSTED_REPORTS], reliability=0.92),
            EvidenceItem(id="comment_reactions", title="Forum comments", summary="Several commenters say the video feels real because of weather and uniforms.", supports_truth=False, useful_actions=[ActionType.REQUEST_CONTEXT], reliability=0.18, distractor=True),
        ],
    ),
    Scenario(
        id="medium_refugee_numbers",
        difficulty=Difficulty.MEDIUM,
        claim="Post says 200,000 people fled the city overnight after chemical attack rumors.",
        source_name="Breaking Signal",
        source_type="telegram channel",
        region="Aleppo",
        timestamp="2026-04-04T08:10:00Z",
        verdict=Verdict.INSUFFICIENT,
        rationale="There are early reports of panic movement, but reliable agencies have not confirmed numbers or the attack basis yet.",
        evidence=[
            EvidenceItem(id="channel_reputation", title="Channel reputation", summary="Channel posts genuine eyewitness clips but rarely verifies displacement counts.", supports_truth=True, useful_actions=[ActionType.INSPECT_SOURCE], reliability=0.68),
            EvidenceItem(id="aid_agency_update", title="Aid agency note", summary="Humanitarian teams confirm increased movement but call the 200,000 number unverified.", supports_truth=True, useful_actions=[ActionType.CROSSCHECK_TRUSTED_REPORTS], reliability=0.91),
            EvidenceItem(id="timeline_gap", title="Reporting gap", summary="No reliable source can account for overnight totals yet.", supports_truth=True, useful_actions=[ActionType.CHECK_TIMELINE, ActionType.REQUEST_CONTEXT], reliability=0.88),
        ],
    ),
    Scenario(
        id="medium_recycled_protest_clip",
        difficulty=Difficulty.MEDIUM,
        claim="Clip shows civilians protesting new wartime food rationing policy in the capital this morning.",
        source_name="CivicPulse24",
        source_type="microblog account",
        region="Tbilisi",
        timestamp="2026-04-04T07:55:00Z",
        verdict=Verdict.MISLEADING,
        rationale="The protest is real, but the clip is from an older fuel-price demonstration and is being relabeled as food-ration unrest.",
        evidence=[
            EvidenceItem(id="account_pattern", title="Account pattern", summary="Account often republishes clips with light edits and dramatic captions.", supports_truth=True, useful_actions=[ActionType.INSPECT_SOURCE], reliability=0.76),
            EvidenceItem(id="clip_archive", title="Archived clip match", summary="Distinct banner and building angle match a protest video from the previous year.", supports_truth=True, useful_actions=[ActionType.ANALYZE_MEDIA, ActionType.CHECK_TIMELINE], reliability=0.95),
            EvidenceItem(id="policy_report", title="Policy reporting", summary="Trusted outlets report rationing debates but no morning protest at the cited location.", supports_truth=True, useful_actions=[ActionType.CROSSCHECK_TRUSTED_REPORTS], reliability=0.89),
            EvidenceItem(id="caption_tone", title="Caption exaggeration", summary="Caption claims 'capital erupts' even though the clip shows a limited street crowd.", supports_truth=True, useful_actions=[ActionType.SCAN_LANGUAGE], reliability=0.67),
        ],
    ),
    Scenario(
        id="hard_deepfake_surrender",
        difficulty=Difficulty.HARD,
        claim="Leaked video shows a senior general announcing surrender and immediate troop withdrawal.",
        source_name="ShadowIntelLeaks",
        source_type="anonymous leak channel",
        region="Donbas",
        timestamp="2026-04-02T22:40:00Z",
        verdict=Verdict.FAKE,
        rationale="The clip is synthetic, with lip-sync irregularities and no confirmation from any reliable source.",
        evidence=[
            EvidenceItem(id="anon_source", title="Anonymous leak source", summary="Channel offers no provenance and previously shared edited audio.", supports_truth=True, useful_actions=[ActionType.INSPECT_SOURCE], reliability=0.77),
            EvidenceItem(id="deepfake_markers", title="Media forensics", summary="Facial boundary flicker and unnatural audio transitions suggest synthesis.", supports_truth=True, useful_actions=[ActionType.ANALYZE_MEDIA], reliability=0.97),
            EvidenceItem(id="timeline_conflict", title="Timeline conflict", summary="General was verified speaking live elsewhere during the claimed recording window.", supports_truth=True, useful_actions=[ActionType.CHECK_TIMELINE], reliability=0.96),
            EvidenceItem(id="no_official_match", title="No trusted confirmation", summary="No recognized defense or international outlet corroborates a surrender order.", supports_truth=True, useful_actions=[ActionType.CROSSCHECK_TRUSTED_REPORTS], reliability=0.93),
        ],
    ),
    Scenario(
        id="hard_staged_relief_warehouse",
        difficulty=Difficulty.HARD,
        claim="Thread alleges aid groups are staging empty warehouse photos and stealing relief supplies.",
        source_name="PeopleFirstWarDesk",
        source_type="influencer account",
        region="Port Sudan",
        timestamp="2026-04-03T11:35:00Z",
        verdict=Verdict.MISLEADING,
        rationale="One warehouse photo lacked context, but the broader claim of systematic theft is unsupported.",
        evidence=[
            EvidenceItem(id="influencer_track", title="Influencer posting track", summary="Account mixes activism with unverified allegations and seldom issues corrections.", supports_truth=True, useful_actions=[ActionType.INSPECT_SOURCE], reliability=0.73),
            EvidenceItem(id="warehouse_context", title="Context on warehouse image", summary="The 'empty' image was taken before a scheduled delivery window.", supports_truth=True, useful_actions=[ActionType.REQUEST_CONTEXT, ActionType.CHECK_TIMELINE], reliability=0.9),
            EvidenceItem(id="inventory_records", title="Inventory and delivery logs", summary="Logs and partner sign-offs show supplies moved to clinics that same day.", supports_truth=True, useful_actions=[ActionType.CROSSCHECK_TRUSTED_REPORTS], reliability=0.95),
            EvidenceItem(id="narrative_language", title="Narrative escalation", summary="Thread jumps from one image to a sweeping accusation of systematic theft.", supports_truth=True, useful_actions=[ActionType.SCAN_LANGUAGE], reliability=0.69),
        ],
    ),
    Scenario(
        id="hard_conflicting_blackout_claim",
        difficulty=Difficulty.HARD,
        claim="Officials are hiding a nationwide blackout after cyberattacks; all major grids are down.",
        source_name="EmergencyTruthHub",
        source_type="pseudo-news site",
        region="Ukraine",
        timestamp="2026-04-04T19:50:00Z",
        verdict=Verdict.MISLEADING,
        rationale="There are regional outages and cyber incidents, but the claim of total nationwide blackout is false.",
        evidence=[
            EvidenceItem(id="site_pattern", title="Pseudo-news source pattern", summary="Site frequently blends real incidents with inflated national conclusions.", supports_truth=True, useful_actions=[ActionType.INSPECT_SOURCE], reliability=0.82),
            EvidenceItem(id="grid_updates", title="Grid operator updates", summary="Operator confirms outages in two regions while the national grid remains functional.", supports_truth=True, useful_actions=[ActionType.CROSSCHECK_TRUSTED_REPORTS], reliability=0.96),
            EvidenceItem(id="map_screenshots", title="Outage map screenshots", summary="Shared screenshots crop out timestamps and regional labels, making them appear nationwide.", supports_truth=True, useful_actions=[ActionType.ANALYZE_MEDIA, ActionType.REQUEST_CONTEXT], reliability=0.87),
            EvidenceItem(id="fear_language", title="Fear-heavy framing", summary="Headline says 'entire country dark' and 'cover-up exposed' despite local evidence.", supports_truth=True, useful_actions=[ActionType.SCAN_LANGUAGE], reliability=0.74),
        ],
    ),
    Scenario(
        id="hard_false_ceasefire_bulletin",
        difficulty=Difficulty.HARD,
        claim="A polished bulletin says a ceasefire has already been signed and civilians should return home immediately.",
        source_name="Global Peace Monitor",
        source_type="lookalike news site",
        region="Lebanon border",
        timestamp="2026-04-05T05:40:00Z",
        verdict=Verdict.FAKE,
        rationale="The bulletin imitates a news brand, but no agreement exists and the site uses copied branding to spread dangerous misinformation.",
        evidence=[
            EvidenceItem(id="brand_spoof", title="Brand spoof indicators", summary="Domain name and visual style mimic a real outlet but contact and about pages are fabricated.", supports_truth=True, useful_actions=[ActionType.INSPECT_SOURCE], reliability=0.94),
            EvidenceItem(id="ceasefire_denial", title="Negotiation status", summary="Diplomatic and military reporters confirm talks are ongoing with no signed ceasefire.", supports_truth=True, useful_actions=[ActionType.CROSSCHECK_TRUSTED_REPORTS], reliability=0.97),
            EvidenceItem(id="return_home_language", title="Harmful instruction pattern", summary="Bulletin includes direct safety instructions unsupported by any authority.", supports_truth=True, useful_actions=[ActionType.SCAN_LANGUAGE, ActionType.REQUEST_CONTEXT], reliability=0.81),
            EvidenceItem(id="publish_timeline", title="Publish timeline anomaly", summary="The article appeared minutes after templated placeholder pages were created on the spoof domain.", supports_truth=True, useful_actions=[ActionType.CHECK_TIMELINE], reliability=0.9),
        ],
    ),
    Scenario(
        id="hard_satellite_image_spin",
        difficulty=Difficulty.HARD,
        claim="Satellite image proves a humanitarian camp was intentionally burned by aid workers to hide theft.",
        source_name="IntelExpose",
        source_type="pseudo-investigative blog",
        region="Darfur",
        timestamp="2026-04-05T09:20:00Z",
        verdict=Verdict.MISLEADING,
        rationale="The image does show fire damage, but attribution to aid workers is unsupported and contradicted by field reporting about nearby shelling.",
        evidence=[
            EvidenceItem(id="blog_history", title="Blog credibility history", summary="Outlet selectively interprets imagery and tends to overstate causal claims.", supports_truth=True, useful_actions=[ActionType.INSPECT_SOURCE], reliability=0.79),
            EvidenceItem(id="image_limits", title="Image interpretation limits", summary="The satellite frame shows burn scars but cannot identify who caused them.", supports_truth=True, useful_actions=[ActionType.ANALYZE_MEDIA], reliability=0.92),
            EvidenceItem(id="field_reports", title="Field reports", summary="Aid partners and journalists documented shelling near the camp during the same period.", supports_truth=True, useful_actions=[ActionType.CROSSCHECK_TRUSTED_REPORTS, ActionType.CHECK_TIMELINE], reliability=0.93),
            EvidenceItem(id="causal_leap", title="Causal leap in narrative", summary="Post jumps from visual evidence of burning to a theft cover-up accusation.", supports_truth=True, useful_actions=[ActionType.SCAN_LANGUAGE], reliability=0.72),
        ],
    ),
]


def get_scenarios() -> list[Scenario]:
    return list(SCENARIOS)
